package Vista;

import Control.SQL;
import Modelo.CitasC;
import Modelo.ClientesC;
import Modelo.ServiciosC;
import Modelo.UsuariosC;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author j_k_h
 */
public class CitasArea extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public CitasArea() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/icono.jpeg")).getImage());
        
    }
    int rez=0;
    String nombre="", prioridad="", usuario="", area="", contraseña="", nombreTemporal="", idTemporal="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtfBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jcbArea = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jcbDia = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbAño = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jcbHora = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jcbServicio = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jtfCosto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jcbEstadoPago = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jtfFolioUF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jtfFolioSCE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jcbAtendera = new javax.swing.JComboBox<>();

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Area"
            }
        ));
        jScrollPane2.setViewportView(tabla2);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Ponguinguiola Chico.png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Titulo.setText("Citas");

        btnVolver.setBackground(new java.awt.Color(10, 76, 142));
        btnVolver.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Cliente:");

        jtfBuscar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyReleased(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(10, 76, 142));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(10, 76, 142));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(10, 76, 142));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Cliente:");

        jtfNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("Area:");

        jcbArea.setBackground(new java.awt.Color(10, 76, 142));
        jcbArea.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbArea.setForeground(new java.awt.Color(255, 255, 255));
        jcbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar", "Recepción.", "Administración.", "Vinculación y Relaciones Públicas.", "Biblioteca/Cineclub.", "Buffete Contable.", "Buffete Jurídico.", "Psicoeducativo.", "Fisioterapia.", "Nutrición.", "Centro de acopio.", " " }));
        jcbArea.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Fecha:");

        jcbDia.setBackground(new java.awt.Color(10, 76, 142));
        jcbDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbDia.setForeground(new java.awt.Color(255, 255, 255));
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jcbMes.setBackground(new java.awt.Color(10, 76, 142));
        jcbMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbMes.setForeground(new java.awt.Color(255, 255, 255));
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jcbAño.setBackground(new java.awt.Color(10, 76, 142));
        jcbAño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbAño.setForeground(new java.awt.Color(255, 255, 255));
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setText("Hora:");

        jcbHora.setBackground(new java.awt.Color(10, 76, 142));
        jcbHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbHora.setForeground(new java.awt.Color(255, 255, 255));
        jcbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00 am.", "07:30 am.", "08:00 am.", "08:30 am.", "09:00 am.", "09:30 am.", "10:00 am.", "10:30 am.", "11:00 am.", "11:30 am.", "12:00 pm.", "12:30 pm.", "01:00 pm.", "01:30 pm.", "02:00 pm.", "02:30 pm.", "03:00 pm.", "03:30 pm.", "04:00 pm.", "04:30 pm.", "05:00 pm.", "05:30 pm.", "06:00 pm.", "06:30 pm.", "07:00 pm.", "07:30 pm.", "08:00 pm.", "08:30 pm." }));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("Estado:");

        jcbEstado.setBackground(new java.awt.Color(10, 76, 142));
        jcbEstado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Cumplida", "No asistió" }));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setText("Atenderá:");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setText("Servicio ofrecido:");

        jcbServicio.setBackground(new java.awt.Color(10, 76, 142));
        jcbServicio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbServicio.setForeground(new java.awt.Color(255, 255, 255));
        jcbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicios sin especificar" }));
        jcbServicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbServicioItemStateChanged(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setText("Costo:");

        jtfCosto.setEditable(false);
        jtfCosto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfCosto.setEnabled(false);
        jtfCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCostoActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setText("Estado de pago:");

        jcbEstadoPago.setBackground(new java.awt.Color(10, 76, 142));
        jcbEstadoPago.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbEstadoPago.setForeground(new java.awt.Color(255, 255, 255));
        jcbEstadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagado", "No Pagado" }));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setText("Folio UF:");

        jtfFolioUF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setText("Folio SCE:");

        jtfFolioSCE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "José Luis Gómez Figueroa", "Admin", "Sin especificar", null}
            },
            new String [] {
                "Id", "Cliente", "Area", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jButton1.setBackground(new java.awt.Color(10, 76, 142));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbAtendera.setBackground(new java.awt.Color(10, 76, 142));
        jcbAtendera.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbAtendera.setForeground(new java.awt.Color(255, 255, 255));
        jcbAtendera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin especificar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(27, 27, 27)
                                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel29)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jtfFolioUF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(233, 233, 233))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jLabel20))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jcbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jcbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jcbAtendera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(108, 108, 108)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel28)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jcbEstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel26)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jcbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel30)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jtfFolioSCE, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Titulo)
                                .addGap(253, 253, 253))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(677, 677, 677))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Titulo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jcbAtendera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jtfFolioUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel19)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbEstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jtfFolioSCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnAgregar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased
        int r = tabla.rowAtPoint(evt.getPoint());
        String elId = tabla.getValueAt(r, 0)+"";

        CitasC u = new CitasC();
        u.setId(elId);
        int error=0;
        try {
            u.cargarDatos2(SQL.ejecutaQ(u.buscarID("id",elId), this,0));
        } catch (SQLException ex) {
        }

        nombreTemporal=u.getCliente();
        idTemporal=elId;

        jtfNombre.setText(u.getCliente());
        jcbAtendera.setSelectedItem(u.getAtendera());
        jtfFolioUF.setText(u.getFolioUF());
        jtfFolioSCE.setText(u.getFolioSCE());
        jtfCosto.setText(u.getCosto());
        jcbArea.setSelectedItem(u.getArea());
        String cadena = u.getFecha();
        jcbHora.setSelectedItem(u.getHora());
        jcbEstado.setSelectedItem(u.getEstado());
        jcbEstadoPago.setSelectedItem(u.getEstadoDePago());
        jcbServicio.setSelectedItem(u.getServicio());

        String numero = "", año="", mes="";
        boolean n=false;
        int m = 0;
        for(int a = 0;a<cadena.length();a++){
            String ejemplo = cadena.charAt(a)+"";
            if(m==2){
                if(ejemplo.compareTo("y")==0){
                    mes="Mayo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("r")==0){
                    mes="Marzo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("n")==0){
                    mes="Junio";
                    n=true;
                    m=0;
                }
                
                else if (ejemplo.compareTo("l")==0){
                    mes="Julio";
                    n=true;
                    m=0;
                }
            }
            if(m==1){
                m=2;
                if (ejemplo.compareTo("b")==0){
                    mes="Abril";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("g")==0){
                    mes="Agosto";
                    n=true;
                    m=0;
                }
            }
            if(ejemplo.compareTo("1")==0){
                if(n==false){
                    numero=numero+"1";
                }
                else{
                    año=año+"1";
                }
            }
            if(ejemplo.compareTo("2")==0){
                if(n==false){
                    numero=numero+"2";
                }
                else{
                    año=año+"2";
                }
            }
            if(ejemplo.compareTo("3")==0){
                if(n==false){
                    numero=numero+"3";
                }
                else{
                    año=año+"3";
                }
            }
            if(ejemplo.compareTo("4")==0){
                if(n==false){
                    numero=numero+"4";
                }
                else{
                    año=año+"4";
                }
            }
            if(ejemplo.compareTo("5")==0){
                if(n==false){
                    numero=numero+"5";
                }
                else{
                    año=año+"5";
                }
            }
            if(ejemplo.compareTo("6")==0){
                if(n==false){
                    numero=numero+"6";
                }
                else{
                    año=año+"6";
                }
            }
            if(ejemplo.compareTo("7")==0){
                if(n==false){
                    numero=numero+"7";
                }
                else{
                    año=año+"7";
                }
            }
            if(ejemplo.compareTo("8")==0){
                if(n==false){
                    numero=numero+"8";
                }
                else{
                    año=año+"8";
                }
            }
            if(ejemplo.compareTo("9")==0){
                if(n==false){
                    numero=numero+"9";
                }
                else{
                    año=año+"9";
                }
            }
            if(ejemplo.compareTo("0")==0){
                if(n==false){
                    numero=numero+"0";
                }
                else{
                    año=año+"0";
                }
            }
            if(ejemplo.compareTo("E")==0){
                mes="Enero";
                n=true;
            }
            if(ejemplo.compareTo("F")==0){
                mes="Febrero";
                n=true;
            }
            if(ejemplo.compareTo("D")==0){
                mes="Diciembre";
                n=true;
            }
            if(ejemplo.compareTo("S")==0){
                mes="Septiembre";
                n=true;
            }
            if(ejemplo.compareTo("O")==0){
                mes="Octubre";
                n=true;
            }
            if(ejemplo.compareTo("N")==0){
                mes="Noviembre";
                n=true;
            }
            if(ejemplo.compareTo("M")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("A")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("J")==0){
                m=1;
                n=true;
            }
        }
        jcbDia.setSelectedItem(numero);
        jcbMes.setSelectedItem(mes);
        jcbAño.setSelectedItem(año);
    }//GEN-LAST:event_tablaMouseReleased

    private void jtfCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCostoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar esta cita?"
                , "Confirmar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            Eliminar();
        }
        else{
                }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar los cambios en esta cita?"
                , "Confirmar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            Modificar();
        }
        else{
                }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea agregar esta nueva cita?"
                , "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            Agregar();
        }
        else{
                }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuRecepcion menu = new MenuRecepcion();
        menu.setVisible(true);
        menu.datos(nombre,prioridad,usuario,area,contraseña);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyReleased
        String s;
        CitasC n = new CitasC();
        try{
        s = n.buscarID5("cliente",jtfBuscar.getText(),"area",(area+"."));
        n.cargarDatos3(SQL.ejecutaQ(s, this,0),(DefaultTableModel)tabla.getModel());
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problema de captura", "Pagina de error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
        System.out.println(""+this.getSize());
        System.out.println(jPanel1.getSize());
    }//GEN-LAST:event_jtfBuscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Point punto = MouseInfo.getPointerInfo().getLocation();
        int x = punto.x;
        int y = punto.y;
        ListaClientesA u = new ListaClientesA();
        u.setVisible(true);
        u.iniciar(x, y, this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        if(rez==0){
            System.out.println(""+this.getSize());
            System.out.println(jPanel1.getSize());
            this.setSize(jPanel1.getWidth()+20,jPanel1.getHeight()+20);
            System.out.println(""+this.getSize());
            System.out.println(jPanel1.getSize());
            rez=1;
        }
        
    }//GEN-LAST:event_jPanel1ComponentResized

    private void jcbServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbServicioItemStateChanged
        ServiciosC c = new ServiciosC();
        c.setNombreDelServicio(jcbServicio.getSelectedItem()+"");
        String dato = c.buscarID2();
        
        try {
            c.cargarDatos2(SQL.ejecutaQ(dato, this,0));
        } catch (SQLException ex) {
        }
        jtfCosto.setText(c.getCosto());
    }//GEN-LAST:event_jcbServicioItemStateChanged

    public void Agregar(){
        String sql="INSERT INTO `ponguibd`.`citas` (`cliente`, `area`, `fecha`, `hora`, `atendera`, `folioUF`, `estado`,"
                + " `servicio`, `costo`, `estadoDePago`, `folioSCE`) VALUES ('"+jtfNombre.getText()+"', '"+jcbArea.getSelectedItem()+""
                + "', '"+jcbDia.getSelectedItem()+" de "+jcbMes.getSelectedItem()+" del "+jcbAño.getSelectedItem()+"', "
                + "'"+jcbHora.getSelectedItem()+"', '"+jcbAtendera.getSelectedItem()+"', '"+jtfFolioUF.getText()+"', "
                + "'"+jcbEstado.getSelectedItem()+"', '"+jcbServicio.getSelectedItem()+"', '"+jtfCosto.getText()+"', "
                + "'"+jcbEstadoPago.getSelectedItem()+"', '"+jtfFolioSCE.getText()+"');";
        SQL.ejecuta(sql,this,0);
        iniciar();
    }
    
    public void Modificar(){
        CitasC u = new CitasC();
        
        try {
            u.cargarDatos2(SQL.ejecutaQ(u.buscarID("id",idTemporal), this,0));
        } catch (SQLException ex) {
        }
        String sql="UPDATE `ponguibd`.`citas` SET `cliente` = '"+jtfNombre.getText()+"', `area` = '"+jcbArea.getSelectedItem()+"', "
                + "`fecha` = '"+jcbDia.getSelectedItem()+" de "+jcbMes.getSelectedItem()+" del "+jcbAño.getSelectedItem()+""
                + "', `hora` = '"+jcbHora.getSelectedItem()+"', `atendera` = '"+jcbAtendera.getSelectedItem()+"', "
                + "`folioUF` = '"+jtfFolioUF.getText()+"', `estado` = '"+jcbEstado.getSelectedItem()+"', `servicio` = '"+jcbServicio.getSelectedItem()+"',"
                + " `costo` = '"+jtfCosto.getText()+"', `estadoDePago` = '"+jcbEstadoPago.getSelectedItem()+""
                + "', `folioSCE` = '"+jtfFolioSCE.getText()+"' WHERE (`id` = '"+u.getId()+"');\n";
        SQL.ejecuta(sql,this,0);
        iniciar();
    }
    
    public void Eliminar(){
        CitasC u = new CitasC();
        
        try {
            u.cargarDatos2(SQL.ejecutaQ(u.buscarID("id",idTemporal), this,0));
        } catch (SQLException ex) {
        }
        String sql = "DELETE FROM `ponguibd`.`citas` WHERE (`id` = '"+u.getId()+"');";
        SQL.ejecuta(sql,this,0);
        iniciar();
    }
    
    public void iniciar(){
        String s;
        CitasC n = new CitasC();
        n.setArea(area+".");
        try{
        s = n.buscarID4();
        n.cargarDatos3(SQL.ejecutaQ(s, this,0),(DefaultTableModel)tabla.getModel());
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problema de captura", "Pagina de error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        jcbArea.setSelectedItem(area+".");
        
        if(rez==0){
            ServiciosC m = new ServiciosC();
            try{
            s = m.buscarID("id","");
            m.cargarDatos4(SQL.ejecutaQ(s, this,0),(DefaultTableModel)tabla2.getModel());
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Problema de captura", "Pagina de error", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
            }
            int num = tabla2.getRowCount();
            System.out.println(num+"");
            for(int a =0; a<num; a++){
                System.out.println(tabla2.getValueAt(a, 0));
                String ar = tabla2.getValueAt(a,1)+"";
                if(ar.compareTo(area+".")==0||ar.compareTo(area+"")==0){
                    jcbServicio.addItem(tabla2.getValueAt(a, 0)+"");
                }
            }
            
            UsuariosC x = new UsuariosC();
            try{
            s = x.buscarID5("id","","area",area);
            x.cargarDatos3(SQL.ejecutaQ(s, this,0),(DefaultTableModel)tabla3.getModel());
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Problema de captura", "Pagina de error", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
            }
            num = tabla3.getRowCount();
            System.out.println(num+"");
            for(int a =0; a<num; a++){
                System.out.println(tabla3.getValueAt(a, 0));
                jcbAtendera.addItem(tabla3.getValueAt(a, 0)+"");
            }
        }
        
        
    }
    
    public void datos(String n, String p, String u, String a, String c){
        nombre=n;
        prioridad=p;
        usuario=u;
        area=a;
        contraseña=c;
    }
    
    public void clientito(String a){
        jtfNombre.setText(a);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitasArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitasArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitasArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitasArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitasArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JComboBox<String> jcbArea;
    private javax.swing.JComboBox<String> jcbAtendera;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbEstadoPago;
    private javax.swing.JComboBox<String> jcbHora;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbServicio;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfCosto;
    private javax.swing.JTextField jtfFolioSCE;
    private javax.swing.JTextField jtfFolioUF;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    // End of variables declaration//GEN-END:variables
}
