package Vista;

import Control.SQL;
import Modelo.VoluntariosC;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author j_k_h
 */
public class VoluntariadoModificarArea extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public VoluntariadoModificarArea() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/icono.jpeg")).getImage());
        this.setResizable(false);
    }
    
    String nombre="", prioridad="", usuario="", area="", contraseña="",newId="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jcbArea = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNombres = new javax.swing.JTextField();
        jtfClave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfApellidoP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfApellidoM = new javax.swing.JTextField();
        jtfHorasReq = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfPlan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfKilos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jrbHombre = new javax.swing.JRadioButton();
        jrbMujer = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jtfEdad = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jcbEscuela = new javax.swing.JComboBox<>();
        jrbPrepa = new javax.swing.JRadioButton();
        jrbUni = new javax.swing.JRadioButton();
        btnCerrarSesion1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jtfEspecialidad = new javax.swing.JTextField();
        jrbMatutino = new javax.swing.JRadioButton();
        jrbVespertino = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jtfSemestre = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtfGrupo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtfTelefonoFIjo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jtfCelular = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jtfCorreo = new javax.swing.JTextField();
        jcbDia = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbAño = new javax.swing.JComboBox<>();
        jcbDia1 = new javax.swing.JComboBox<>();
        jcbMes1 = new javax.swing.JComboBox<>();
        jcbAño1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Ponguinguiola Chico.png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Titulo.setText("Modificar voluntario");

        btnCerrarSesion.setBackground(new java.awt.Color(10, 76, 142));
        btnCerrarSesion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Volver");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        jcbArea.setBackground(new java.awt.Color(10, 76, 142));
        jcbArea.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbArea.setForeground(new java.awt.Color(255, 255, 255));
        jcbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepción.", "Sin Especificar", "Administración.", "Vinculación y Relaciones Públicas.", "Biblioteca/Cineclub.", "Buffete Contable.", "Buffete Jurídico.", "Psicoeducativo.", "Fisioterapia.", "Nutrición.", "Centro de acopio.", " " }));
        jcbArea.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Area Designada:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Nombres:");

        jtfNombres.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombresActionPerformed(evt);
            }
        });

        jtfClave.setEditable(false);
        jtfClave.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfClave.setText("02536");
        jtfClave.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Clave:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Apellido paterno:");

        jtfApellidoP.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoPActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Apellido materno:");

        jtfApellidoM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoMActionPerformed(evt);
            }
        });

        jtfHorasReq.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfHorasReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHorasReqActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("Horas requeridas:");

        jtfPlan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPlanActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("Horas del plan:");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setText("Kg. del plan:");

        jtfKilos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfKilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKilosActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Fecha de ingreso:");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("Estado:");

        jcbEstado.setBackground(new java.awt.Color(10, 76, 142));
        jcbEstado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Liberado completo", "Liberado", "Baja", "Inactivo", " " }));

        buttonGroup1.add(jrbHombre);
        jrbHombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbHombre.setText("Hombre");

        buttonGroup1.add(jrbMujer);
        jrbMujer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbMujer.setText("Mujer");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Edad:");

        jtfEdad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEdadActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setText("Fecha de nacimiento:");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel23.setText("Escuela:");

        jcbEscuela.setBackground(new java.awt.Color(10, 76, 142));
        jcbEscuela.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jcbEscuela.setForeground(new java.awt.Color(255, 255, 255));
        jcbEscuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CBTIS 37", "CBTIS 188", "CBTA 197", "CETEMAR", "CONALEP", "COLEGIO OBREGON", "INSTITUTO LASALLE", "INSTITUTO ESPINOZA", "ITSON", "ITESCA", "TECNOLOGICO DE MONTERREY", "INST. CUMBRE NOROESTE", "ULSA", "UNID", " ", " " }));

        buttonGroup2.add(jrbPrepa);
        jrbPrepa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbPrepa.setText("Preparatoria");

        buttonGroup2.add(jrbUni);
        jrbUni.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbUni.setSelected(true);
        jrbUni.setText("Universidad");

        btnCerrarSesion1.setBackground(new java.awt.Color(10, 76, 142));
        btnCerrarSesion1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnCerrarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion1.setText("Modificar voluntario");
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("Especialidad:");

        jtfEspecialidad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEspecialidadActionPerformed(evt);
            }
        });

        buttonGroup3.add(jrbMatutino);
        jrbMatutino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbMatutino.setSelected(true);
        jrbMatutino.setText("Matutino");

        buttonGroup3.add(jrbVespertino);
        jrbVespertino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jrbVespertino.setText("Vespertino");

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setText("Semestre:");

        jtfSemestre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSemestreActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setText("Grupo:");

        jtfGrupo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGrupoActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setText("Matricula:");

        jtfMatricula.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMatriculaActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setText("Telefono fijo:");

        jtfTelefonoFIjo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfTelefonoFIjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoFIjoActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setText("Telefono Celular:");

        jtfCelular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCelularActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setText("Correo:");

        jtfCorreo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCorreoActionPerformed(evt);
            }
        });

        jcbDia.setBackground(new java.awt.Color(10, 76, 142));
        jcbDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbDia.setForeground(new java.awt.Color(255, 255, 255));
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jcbMes.setBackground(new java.awt.Color(10, 76, 142));
        jcbMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbMes.setForeground(new java.awt.Color(255, 255, 255));
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jcbAño.setBackground(new java.awt.Color(10, 76, 142));
        jcbAño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbAño.setForeground(new java.awt.Color(255, 255, 255));
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", " " }));

        jcbDia1.setBackground(new java.awt.Color(10, 76, 142));
        jcbDia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbDia1.setForeground(new java.awt.Color(255, 255, 255));
        jcbDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jcbMes1.setBackground(new java.awt.Color(10, 76, 142));
        jcbMes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbMes1.setForeground(new java.awt.Color(255, 255, 255));
        jcbMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jcbAño1.setBackground(new java.awt.Color(10, 76, 142));
        jcbAño1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbAño1.setForeground(new java.awt.Color(255, 255, 255));
        jcbAño1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31)
                                .addComponent(jcbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbHombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbMujer))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtfApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel17))
                                            .addGap(37, 37, 37)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtfHorasReq, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(88, 88, 88)
                                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbAño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))))
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTelefonoFIjo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfMatricula))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbPrepa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbUni)))
                                .addGap(18, 18, 18)
                                .addComponent(jrbMatutino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbVespertino)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfHorasReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtfPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtfKilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbAño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtfApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbHombre)
                            .addComponent(jrbMujer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jtfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbPrepa)
                    .addComponent(jrbUni)
                    .addComponent(jrbMatutino)
                    .addComponent(jrbVespertino)
                    .addComponent(jLabel25)
                    .addComponent(jtfSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jtfGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jtfTelefonoFIjo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnCerrarSesion1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoMActionPerformed

    private void jtfApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoPActionPerformed

    private void jtfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombresActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        VoluntariadoArea u = new VoluntariadoArea();
        u.setVisible(true);
        u.datos(nombre,prioridad,usuario,area,contraseña);
        u.iniciar();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jtfHorasReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHorasReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHorasReqActionPerformed

    private void jtfPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPlanActionPerformed

    private void jtfKilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKilosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKilosActionPerformed

    private void jtfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEdadActionPerformed

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea modificar a este usuario?"
                , "Confirmar Acción", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            Modificar();
        }
        else{
                }
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed

    private void jtfEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEspecialidadActionPerformed

    private void jtfSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSemestreActionPerformed

    private void jtfGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfGrupoActionPerformed

    private void jtfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMatriculaActionPerformed

    private void jtfTelefonoFIjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoFIjoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoFIjoActionPerformed

    private void jtfCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCelularActionPerformed

    private void jtfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorreoActionPerformed

    public void Modificar(){
        
        String nacimiento = jcbDia.getSelectedItem()+" de "+jcbMes.getSelectedItem()+" del "+jcbAño.getSelectedItem();
        String ingreso = jcbDia1.getSelectedItem()+" de "+jcbMes1.getSelectedItem()+" del "+jcbAño1.getSelectedItem();
        
        String sexo = "Hombre", turno = "Matutino", tipoEscuela="Ninguno";
        String nombres = jtfNombres.getText(), apellidoP = jtfApellidoP.getText(), apellidoM = jtfApellidoM.getText(), edad=jtfEdad.getText(),
                fecNac=nacimiento, escuela = (jcbEscuela.getSelectedItem()+""),especialidad = jtfEspecialidad.getText(),
                semestre = jtfSemestre.getText(), grupo = jtfGrupo.getText(), matricula = jtfMatricula.getText(), telefono = jtfTelefonoFIjo.getText(),
                celular=jtfCelular.getText(), correo=jtfCorreo.getText(), area2 = (""+jcbArea.getSelectedItem()), horasR = jtfHorasReq.getText(),
                plan = jtfPlan.getText(),kilos = jtfKilos.getText(), fechaIn=ingreso, estado = (""+jcbEstado.getSelectedItem()),
                nombreCompleto = (nombres+" "+apellidoP+" "+apellidoM), horasContadas="0";
        if(jrbHombre.isSelected()){
            sexo="Hombre";
        }
        else if(jrbMujer.isSelected()){
            sexo="Mujer";
        }
        if(jrbPrepa.isSelected()){
            tipoEscuela="Preparatoria";
        }
        else if(jrbUni.isSelected()){
            tipoEscuela="Universidad";
        }
        if(jrbMatutino.isSelected()){
            turno="Matutino";
        }
        else if(jrbVespertino.isSelected()){
            turno="Vespertino";
        }
        
        
        String sql="UPDATE `ponguibd`.`voluntarios` SET `nombres` = '"+nombres+"', `apellidoPaterno` = '"+apellidoP+"', "
                + "`apellidoMaterno` = '"+apellidoM+"', `sexo` = '"+sexo+"', `edad` = '"+edad+"', `fechaDeNacimiento` = '"+fecNac+"',"
                + " `nombreEscuela` = '"+escuela+"', `especialidad` = '"+especialidad+"', `tipoEscuela` = '"+tipoEscuela+"',"
                + " `turno` = '"+turno+"', `semestre` = '"+semestre+"', `grupo` = '"+grupo+"', `matricula` = '"+matricula+"',"
                + " `telefono` = '"+telefono+"', `celular` = '"+celular+"', `correo` = '"+correo+"', `area` = '"+area2+"',"
                + " `horasRequeridas` = '"+horasR+"', `horasPlan` = '"+plan+"', `kilosR` = '"+kilos+"', `fechaIngreso` = '"+fechaIn+"',"
                + " `estado` = '"+estado+"', `nombreCompleto` = '"+nombreCompleto+"' WHERE (`id` = '"+newId+"');";
        System.out.println(sql);
        SQL.ejecuta(sql,this,0);
    }
    
    public void datos(String n, String p, String u, String a, String c){
        nombre=n;
        prioridad=p;
        usuario=u;
        area=a;
        contraseña=c;
    }
    
    public void iniciar(String lastId){
        newId = lastId;
        jtfClave.setText(newId);
        VoluntariosC u = new VoluntariosC();
        u.setId(newId);
        try {
            u.cargarDatos2(SQL.ejecutaQ(u.buscarID(), this,0));
        } catch (SQLException ex) {
        }
        jtfNombres.setText(u.getNombres());
        jtfApellidoP.setText(u.getApellidoPaterno());
        jtfApellidoM.setText(u.getApellidoMaterno());
        if(u.getSexo().compareTo("Hombre")==0){
            jrbHombre.setSelected(true);
        }
        else{
            jrbMujer.setSelected(true);
        }
        jtfHorasReq.setText(u.getHorasRequeridas());
        jtfPlan.setText(u.getHorasPlan());
        jtfKilos.setText(u.getKilosR());
        PonerFecha1(u.getFechaIngreso());
        jtfEdad.setText(u.getEdad());
        PonerFecha(u.getFechaDeNacimiento());
        jcbEstado.setSelectedItem(u.getEstado());
        jcbEscuela.setSelectedItem(u.getNombreEscuela());
        jtfEspecialidad.setText(u.getEspecialidad());
        if(u.getTipoEscuela().compareTo("Preparatoria")==0){
            jrbPrepa.setSelected(true);
        }
        else{
            jrbUni.setSelected(true);
        }
        if(u.getTurno().compareTo("Matutino")==0){
            jrbMatutino.setSelected(true);
        }
        else{
            jrbVespertino.setSelected(true);
        }
        jtfSemestre.setText(u.getSemestre());
        jtfGrupo.setText(u.getGrupo());
        jtfMatricula.setText(u.getMatricula());
        jtfTelefonoFIjo.setText(u.getTelefono());
        jtfCelular.setText(u.getCelular());
        jtfCorreo.setText(u.getCorreo());
        jcbArea.setSelectedItem(u.getArea());
    }
    
    
    public void PonerFecha(String cadena){
        
        String numero = "", año="", mes="";
        boolean n=false;
        int m = 0;
        for(int a = 0;a<cadena.length();a++){
            String ejemplo = cadena.charAt(a)+"";
            if(m==2){
                if(ejemplo.compareTo("y")==0){
                    mes="Mayo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("r")==0){
                    mes="Marzo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("n")==0){
                    mes="Junio";
                    n=true;
                    m=0;
                }
                
                else if (ejemplo.compareTo("l")==0){
                    mes="Julio";
                    n=true;
                    m=0;
                }
            }
            if(m==1){
                m=2;
                if (ejemplo.compareTo("b")==0){
                    mes="Abril";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("g")==0){
                    mes="Agosto";
                    n=true;
                    m=0;
                }
            }
            if(ejemplo.compareTo("1")==0){
                if(n==false){
                    numero=numero+"1";
                }
                else{
                    año=año+"1";
                }
            }
            if(ejemplo.compareTo("2")==0){
                if(n==false){
                    numero=numero+"2";
                }
                else{
                    año=año+"2";
                }
            }
            if(ejemplo.compareTo("3")==0){
                if(n==false){
                    numero=numero+"3";
                }
                else{
                    año=año+"3";
                }
            }
            if(ejemplo.compareTo("4")==0){
                if(n==false){
                    numero=numero+"4";
                }
                else{
                    año=año+"4";
                }
            }
            if(ejemplo.compareTo("5")==0){
                if(n==false){
                    numero=numero+"5";
                }
                else{
                    año=año+"5";
                }
            }
            if(ejemplo.compareTo("6")==0){
                if(n==false){
                    numero=numero+"6";
                }
                else{
                    año=año+"6";
                }
            }
            if(ejemplo.compareTo("7")==0){
                if(n==false){
                    numero=numero+"7";
                }
                else{
                    año=año+"7";
                }
            }
            if(ejemplo.compareTo("8")==0){
                if(n==false){
                    numero=numero+"8";
                }
                else{
                    año=año+"8";
                }
            }
            if(ejemplo.compareTo("9")==0){
                if(n==false){
                    numero=numero+"9";
                }
                else{
                    año=año+"9";
                }
            }
            if(ejemplo.compareTo("0")==0){
                if(n==false){
                    numero=numero+"0";
                }
                else{
                    año=año+"0";
                }
            }
            if(ejemplo.compareTo("E")==0){
                mes="Enero";
                n=true;
            }
            if(ejemplo.compareTo("F")==0){
                mes="Febrero";
                n=true;
            }
            if(ejemplo.compareTo("D")==0){
                mes="Diciembre";
                n=true;
            }
            if(ejemplo.compareTo("S")==0){
                mes="Septiembre";
                n=true;
            }
            if(ejemplo.compareTo("O")==0){
                mes="Octubre";
                n=true;
            }
            if(ejemplo.compareTo("N")==0){
                mes="Noviembre";
                n=true;
            }
            if(ejemplo.compareTo("M")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("A")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("J")==0){
                m=1;
                n=true;
            }
        }
        jcbDia.setSelectedItem(numero);
        jcbMes.setSelectedItem(mes);
        jcbAño.setSelectedItem(año);
    }
    
    
    public void PonerFecha1(String cadena){
        
        String numero = "", año="", mes="";
        boolean n=false;
        int m = 0;
        for(int a = 0;a<cadena.length();a++){
            String ejemplo = cadena.charAt(a)+"";
            if(m==2){
                if(ejemplo.compareTo("y")==0){
                    mes="Mayo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("r")==0){
                    mes="Marzo";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("n")==0){
                    mes="Junio";
                    n=true;
                    m=0;
                }
                
                else if (ejemplo.compareTo("l")==0){
                    mes="Julio";
                    n=true;
                    m=0;
                }
            }
            if(m==1){
                m=2;
                if (ejemplo.compareTo("b")==0){
                    mes="Abril";
                    n=true;
                    m=0;
                }
                else if (ejemplo.compareTo("g")==0){
                    mes="Agosto";
                    n=true;
                    m=0;
                }
            }
            if(ejemplo.compareTo("1")==0){
                if(n==false){
                    numero=numero+"1";
                }
                else{
                    año=año+"1";
                }
            }
            if(ejemplo.compareTo("2")==0){
                if(n==false){
                    numero=numero+"2";
                }
                else{
                    año=año+"2";
                }
            }
            if(ejemplo.compareTo("3")==0){
                if(n==false){
                    numero=numero+"3";
                }
                else{
                    año=año+"3";
                }
            }
            if(ejemplo.compareTo("4")==0){
                if(n==false){
                    numero=numero+"4";
                }
                else{
                    año=año+"4";
                }
            }
            if(ejemplo.compareTo("5")==0){
                if(n==false){
                    numero=numero+"5";
                }
                else{
                    año=año+"5";
                }
            }
            if(ejemplo.compareTo("6")==0){
                if(n==false){
                    numero=numero+"6";
                }
                else{
                    año=año+"6";
                }
            }
            if(ejemplo.compareTo("7")==0){
                if(n==false){
                    numero=numero+"7";
                }
                else{
                    año=año+"7";
                }
            }
            if(ejemplo.compareTo("8")==0){
                if(n==false){
                    numero=numero+"8";
                }
                else{
                    año=año+"8";
                }
            }
            if(ejemplo.compareTo("9")==0){
                if(n==false){
                    numero=numero+"9";
                }
                else{
                    año=año+"9";
                }
            }
            if(ejemplo.compareTo("0")==0){
                if(n==false){
                    numero=numero+"0";
                }
                else{
                    año=año+"0";
                }
            }
            if(ejemplo.compareTo("E")==0){
                mes="Enero";
                n=true;
            }
            if(ejemplo.compareTo("F")==0){
                mes="Febrero";
                n=true;
            }
            if(ejemplo.compareTo("D")==0){
                mes="Diciembre";
                n=true;
            }
            if(ejemplo.compareTo("S")==0){
                mes="Septiembre";
                n=true;
            }
            if(ejemplo.compareTo("O")==0){
                mes="Octubre";
                n=true;
            }
            if(ejemplo.compareTo("N")==0){
                mes="Noviembre";
                n=true;
            }
            if(ejemplo.compareTo("M")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("A")==0){
                m=1;
                n=true;
            }
            if(ejemplo.compareTo("J")==0){
                m=1;
                n=true;
            }
        }
        jcbDia1.setSelectedItem(numero);
        jcbMes1.setSelectedItem(mes);
        jcbAño1.setSelectedItem(año);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoluntariadoModificarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoluntariadoModificarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoluntariadoModificarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoluntariadoModificarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoluntariadoModificarArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbArea;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbAño1;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbDia1;
    private javax.swing.JComboBox<String> jcbEscuela;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbMes1;
    private javax.swing.JRadioButton jrbHombre;
    private javax.swing.JRadioButton jrbMatutino;
    private javax.swing.JRadioButton jrbMujer;
    private javax.swing.JRadioButton jrbPrepa;
    private javax.swing.JRadioButton jrbUni;
    private javax.swing.JRadioButton jrbVespertino;
    private javax.swing.JTextField jtfApellidoM;
    private javax.swing.JTextField jtfApellidoP;
    private javax.swing.JTextField jtfCelular;
    private javax.swing.JTextField jtfClave;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfEspecialidad;
    private javax.swing.JTextField jtfGrupo;
    private javax.swing.JTextField jtfHorasReq;
    private javax.swing.JTextField jtfKilos;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNombres;
    private javax.swing.JTextField jtfPlan;
    private javax.swing.JTextField jtfSemestre;
    private javax.swing.JTextField jtfTelefonoFIjo;
    // End of variables declaration//GEN-END:variables
}
